// Single source of truth for the module version = package.json "version".
// This script propagates it to the two places that must match but can't
// reference package.json directly:
//   - companion/manifest.json  (what Companion + the PV server actually ship/compare)
//   - src/version.ts           (imported by main.ts for the module_version variable)
// Run automatically before build/package. Bump ONLY package.json (e.g. `npm version patch`).

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const version = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version

// companion/manifest.json
const manifestPath = join(root, 'companion', 'manifest.json')
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
if (manifest.version !== version) {
    manifest.version = version
    writeFileSync(manifestPath, JSON.stringify(manifest, null, 4) + '\n')
}

// src/version.ts
writeFileSync(
    join(root, 'src', 'version.ts'),
    `// Generated by scripts/sync-version.mjs from package.json — do not edit by hand.\n` +
    `export const MODULE_VERSION = '${version}'\n`,
)

console.log(`sync-version: ${version}`)
